export const MY_PORTFOLIO = {
  AERI3: { quantity: 11, purchasePrice: 2.15, purchaseDate: '' },
  B3SA3: { quantity: 231, purchasePrice: 15.73, purchaseDate: '' },
  BTHF11: { quantity: 339, purchasePrice: 8.85, purchaseDate: '' },
  BCRI11: { quantity: 5, purchasePrice: 59.89, purchaseDate: '' },
  BHIA3: { quantity: 2, purchasePrice: 0.78, purchaseDate: '' },
  BRAP4: { quantity: 22, purchasePrice: 22, purchaseDate: '' },
  CPLE3: { quantity: 990, purchasePrice: 14.83, purchaseDate: '' },
  CSMG3: { quantity: 55, purchasePrice: 64.17, purchaseDate: '' },
  GGBR4: { quantity: 519, purchasePrice: 10.92, purchaseDate: '' },
  GOLD11: { quantity: 26, purchasePrice: 21.36, purchaseDate: '' },
  GRND3: { quantity: 270, purchasePrice: 3.75, purchaseDate: '' },
  HASH11: { quantity: 17, purchasePrice: 41.48, purchaseDate: '' },
  IRBR3: { quantity: 5, purchasePrice: 56.06, purchaseDate: '' },
  IRDM11: { quantity: 35, purchasePrice: 65.09, purchaseDate: '' },
  ISAE4: { quantity: 79, purchasePrice: 26.89, purchaseDate: '' },
  ITSA4: { quantity: 128, purchasePrice: 13.82, purchaseDate: '' },
  LEVE3: { quantity: 20, purchasePrice: 31.88, purchaseDate: '' },
  LOGG3: { quantity: 3, purchasePrice: 25.43, purchaseDate: '' },
  MGLU3: { quantity: 12, purchasePrice: 5.03, purchaseDate: '' },
  MOVI3: { quantity: 10, purchasePrice: 7.88, purchaseDate: '' },
  PETR4: { quantity: 5, purchasePrice: 43.42, purchaseDate: '' },
  PETZ3: { quantity: 114, purchasePrice: 3.49, purchaseDate: '' },
  RBRB11: { quantity: 25, purchasePrice: 37.7, purchaseDate: '' },
  RBRR11: { quantity: 13, purchasePrice: 75.94, purchaseDate: '' },
  RECT11: { quantity: 25, purchasePrice: 35.33, purchaseDate: '' },
  RZAT11: { quantity: 22, purchasePrice: 92.01, purchaseDate: '' },
  ROMI3: { quantity: 50, purchasePrice: 5.87, purchaseDate: '' },
  TAEE11: { quantity: 277, purchasePrice: 39.66, purchaseDate: '' },
  TOTS3: { quantity: 20, purchasePrice: 31.06, purchaseDate: '' },
  VALE3: { quantity: 18, purchasePrice: 76.28, purchaseDate: '' },
  WEGE3: { quantity: 51, purchasePrice: 47.2, purchaseDate: '' },
  XPCM11: { quantity: 68, purchasePrice: 8.04, purchaseDate: '' },
  XPLG11: { quantity: 6, purchasePrice: 92.9, purchaseDate: '' },
  XPIN11: { quantity: 20, purchasePrice: 30.16, purchaseDate: '' },
  XPBR31: { quantity: 3.14768, purchasePrice: 0, purchaseDate: '', currency: 'BRL' },
  XOM: { quantity: 5.2, purchasePrice: 155.49, purchaseDate: '', currency: 'USD' },
  GOOGL: { quantity: 3.504, purchasePrice: 356.13, purchaseDate: '', currency: 'USD' },
  MSFT: { quantity: 1, purchasePrice: 464.72, purchaseDate: '', currency: 'USD' },
  MMM: { quantity: 2.9, purchasePrice: 176.38, purchaseDate: '', currency: 'USD' },
  MCD: { quantity: 0.75, purchasePrice: 270.61, purchaseDate: '', currency: 'USD' },
  JNJ: { quantity: 1, purchasePrice: 256.52, purchaseDate: '', currency: 'USD' },
  CVX: { quantity: 1, purchasePrice: 196.84, purchaseDate: '', currency: 'USD' },
  AAPL: { quantity: 0.807, purchasePrice: 308.91, purchaseDate: '', currency: 'USD' },
  AMZN: { quantity: 0.91, purchasePrice: 271.58, purchaseDate: '', currency: 'USD' },
  NU: { quantity: 14, purchasePrice: 14.33, purchaseDate: '', currency: 'USD' },
  ABNB: { quantity: 0.5855, purchasePrice: 151.52, purchaseDate: '', currency: 'USD' },
  NVDA: { quantity: 1.2222, purchasePrice: 200.75, purchaseDate: '', currency: 'USD' },
  'BRK-B': { quantity: 0.13656, purchasePrice: 511.66, purchaseDate: '', currency: 'USD' },
  BABA: { quantity: 0.377, purchasePrice: 122.28, purchaseDate: '', currency: 'USD' },
  NFLX: { quantity: 0.77, purchasePrice: 71.71, purchaseDate: '', currency: 'USD' },
  TSLA: { quantity: 0.07665, purchasePrice: 311.21, purchaseDate: '', currency: 'USD' },
  COKE: { quantity: 0.2222, purchasePrice: 187.9, purchaseDate: '', currency: 'USD' },
  RBLX: { quantity: 0.233333, purchasePrice: 35.59, purchaseDate: '', currency: 'USD' },
  SPCX: { quantity: 0.55216, purchasePrice: 108.37, purchaseDate: '', currency: 'USD' },
  PEP: { quantity: 0.35, purchasePrice: 139.56, purchaseDate: '', currency: 'USD' },
  EFA: { quantity: 2.98496, purchasePrice: 105.63, purchaseDate: '', currency: 'USD' },
  IAU: { quantity: 1.8116, purchasePrice: 76.17, purchaseDate: '', currency: 'USD' },
  IVV: { quantity: 0.2, purchasePrice: 750.46, purchaseDate: '', currency: 'USD' },
  NOBL: { quantity: 2, purchasePrice: 57.07, purchaseDate: '', currency: 'USD' },
  SPY: { quantity: 0.2, purchasePrice: 746.9, purchaseDate: '', currency: 'USD' },
  SOLV: { quantity: 0.725, purchasePrice: 85.47, purchaseDate: '', currency: 'USD' },
  VNQ: { quantity: 2.69, purchasePrice: 98.92, purchaseDate: '', currency: 'USD' },
  VTI: { quantity: 0.92, purchasePrice: 368.38, purchaseDate: '', currency: 'USD' },
};
