import { seedStocks } from './firebase';

export const INITIAL_STOCKS = {
  AERI3:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  RZAT11: { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  B3SA3:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  BTHF11: { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  BCRI11: { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  BHIA3:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  BRAP4:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  CPLE3:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  CSMG3:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  GGBR4:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  GOLD11: { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  GRND3:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  HASH11: { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  IRBR3:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  IRDM11: { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  ITSA4:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  LEVE3:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  LOGG3:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  MGLU3:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  MOVI3:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  PETR4:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  AUAU3:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  RBRR11: { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  RECT11: { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  ROMI3:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  TAEE11: { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  TOTS3:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  ISAE4:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  VALE3:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  WEGE3:  { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  XPCM11: { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  XPIN11: { quantity: 1, purchasePrice: 0, purchaseDate: '' },
  XOM:    { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  GOOGL:  { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  MSFT:   { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  MMM:    { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  MCD:    { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  JNJ:    { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  CVX:    { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  AAPL:   { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  AMZN:   { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  NU:     { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  ABNB:   { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  NVDA:   { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  'BRK-B': { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  BABA:   { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  NFLX:   { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  TSLA:   { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  COKE:   { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  RBLX:   { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  PEP:    { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  VTI:    { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  EFA:    { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  IAU:    { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  IVV:    { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  NOBL:   { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  SPY:    { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  SOLV:   { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
  VNQ:    { quantity: 1, purchasePrice: 0, purchaseDate: '', currency: 'USD' },
};

export async function seedDefaultStocks() {
  await seedStocks(INITIAL_STOCKS);
}
